# Generated by Django 3.0.5 on 2020-05-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('item', models.CharField(choices=[('course', 'Course'), ('subs', 'Subscription')], max_length=10)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('unpaid', 'unpaid'), ('paid', 'paid')], max_length=20)),
                ('payment', models.CharField(max_length=20)),
            ],
        ),
    ]
