# Generated by Django 3.0.5 on 2020-05-25 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subType', models.CharField(choices=[('monthly', 'Monthly'), ('anually', 'Anually')], max_length=10)),
                ('period', models.IntegerField()),
                ('subID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.Transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
